const $ = selector => document.querySelector(selector);
async function api(url, options = {}) { const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? {} : await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Unable to complete this request.'); return data; }
function renderList(target, rows, render, empty) { $(target).innerHTML = rows.length ? rows.map(render).join('') : `<p class="empty">${empty}</p>`; }
async function loadActivity() { const data = await api('/api/admin/activity'); renderList('#recentSignups', data.signups, row => `<div class="activity-row"><strong>${row.name}</strong><small>${row.email} · Learner #${row.id}</small></div>`, 'No learner sign-ups yet.'); renderList('#recentLogins', data.logins, row => `<div class="activity-row"><strong>${row.name}</strong><small>${row.email} · ${row.login_count} login(s)</small></div>`, 'No learner logins yet.'); renderList('#recentEvents', data.events, row => `<div class="activity-row"><strong>${row.name} · ${row.event_type}</strong><small>${row.email}${row.skill ? ` · ${row.skill}` : ''}${row.score !== null ? ` · Score: ${row.score}` : ''}</small></div>`, 'No practice events yet.'); }
function reveal(email) { $('#adminEmail').textContent = email; $('#adminLogin').classList.add('hidden'); $('#adminDashboard').classList.remove('hidden'); }
$('#adminLoginForm').addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const data = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); reveal(data.admin.email); await loadActivity(); } catch (error) { $('#loginError').textContent = error.message; } });
$('#refreshActivity').addEventListener('click', () => loadActivity().catch(error => alert(error.message)));
$('#adminLogout').addEventListener('click', async () => { try { await api('/api/admin/logout', { method: 'POST' }); } catch (error) {} location.reload(); });
api('/api/admin/session').then(async session => { if (session.authenticated) { reveal(session.admin.email); await loadActivity(); } }).catch(() => {});
